name: Automating tf deployment
on: [push] #list on one line
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest #it is a container image
    steps: #list on multiple lines of steps to take for execution
      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Clone your code in the pipeline
        uses: actions/checkout@v2
      
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false #otherwise terraform output fails
      
      - name: Terraform format
        run: terraform fmt 
        continue-on-error: true
      
      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan
        continue-on-error: true
      
      - name: Terraform apply
        run: terraform apply -auto-approve
        continue-on-error: true
      
      - name: destroy
         run: terraform destroy -auto-approve
      
      # - name: assign ec2 ip to a variable
      #   run: terraform output ec2_instance_ip >> webserver_ip
      
      # - name: update the inventory hosts with the variable value
      #   run: 